const projects = [
    {
        id: 1,
        picture: "./images/swimming.jpg",
        title: "Swimming app",
        description: "Private swimming lessons",
        skill: ["React ", "NodeJS ", "MongoDB"],
        github: "https://github.com/adrijanasavic/frontend_swimming",
        codepen: "",
        link: "https://frontend-swimming.vercel.app/",
    },
    {
        id: 2,
        picture: "./images/portfolio.jpg",
        title: "Portfolio",
        description: "My portfolio",
        skill: ["React ", "NodeJS ", "MongoDB"],
        github: "https://github.com/adrijanasavic/Portfolio-Full_Stack",
        codepen: "",
        link: "",
    },
    {
        id: 3,
        picture: "./images/housemarket.jpg",
        title: "House Marketplace",
        description: "Delivery and rental of houses",
        skill: ["React ", "NodeJS ", "MongoDB"],
        github: "https://github.com/adrijanasavic/House-Marketplace",
        codepen: "",
        link: "https://house-marketplace-teal.vercel.app/",
    },
    {
        id: 4,
        picture: "./images/feedback.jpg",
        title: "Feedback-UI",
        description: "CRUD app.",
        skill: ["React"],
        github: "https://github.com/adrijanasavic/Feedback-UI",
        codepen: "",
        link: "https://feedback-app-react-as.netlify.app/",
    },
    {
        id: 5,
        picture: "./images/metalart.jpg",
        title: "Metal Art",
        description: "Final project on a course at SmartInIT.",
        skill: ["Angular (TypeScript) ", "Firebase"],
        github: "https://github.com/adrijanasavic/MetalArt-Angular",
        codepen: "",
        link: "https://metal-art-angular.netlify.app/",
    },
    {
        id: 6,
        picture: "./images/spacex.jpg",
        title: "SpaceX Land",
        description: "The project made in Angular with API calls.",
        skill: ["Angular (TypeScript) ", "API"],
        github: "https://github.com/adrijanasavic/SpaceX-Land-Angular",
        codepen: "",
        link: "https://spacex-land-angular.netlify.app/",
    },
    {
        id: 7,
        picture: "./images/shop.jpg",
        title: "Shop",
        description: "Project done during the course at SmartInIT.",
        skill: ["Angular (TypeScript) ", "Firebase"],
        github: "https://github.com/adrijanasavic/Shop-app-Angular",
        codepen: "",
        link: "https://shop-app-angular.netlify.app/",
    },
    {
        id: 8,
        picture: "./images/drevna.jpg",
        title: "Restaurant",
        description: "Project for the subject of Web programming",
        skill: ["HTML ", "LESS"],
        github: "https://github.com/adrijanasavic/Restaurant_LESS",
        codepen: "",
        link: "https://drevna.netlify.app/",
    },
    {
        id: 9,
        picture: "./images/novisad.jpg",
        title: "Novi Sad",
        description: "Android app about sights, nature, culture, shopping malls and restaurants in my city.",
        skill: ["Java - Android"],
        github: "https://github.com/adrijanasavic/Novi-Sad",
        codepen: "",
        link: "https://play.google.com/store/apps/details?id=com.ns.novi_sad",
    },
    {
        id: 10,
        picture: "./images/bap.jpg",
        title: "BAP Vesti",
        description: "Informing the public about events from all areas of life.",
        skill: ["Java - Android"],
        github: "https://github.com/adrijanasavic",
        codepen: "",
        link: "https://play.google.com/store/apps/details?id=app.bp",
    },
    {
        id: 11,
        picture: "",
        title: "Final test at FTN",
        description: "Final test at FTN Informatics. Successfully passed with 77%",
        skill: ["Java - Android"],
        github: "https://github.com/adrijanasavic/FTN_Zavrsni_Test",
        link: "https://www.youtube.com/watch?v=bTNHdx3LFXs&ab_channel=AdrijanaJovicicSavic",
    },
    {
        id: 12,
        picture: "",
        title: "Movies and Actors",
        description: "Android app using rest Api.",
        skill: ["Java - Android"],
        github: "https://github.com/adrijanasavic/Movies_and_Actors",
        link: "https://www.youtube.com/watch?v=bBN0-0FToLc&ab_channel=AdrijanaJovicicSavic",
    },
    {
        id: 13,
        picture: "",
        title: "Dental app",
        description: "Android app for scheduling reviews.",
        skill: ["Java - Android"],
        github: "https://github.com/adrijanasavic/Dental_app",
        link: "https://www.youtube.com/watch?v=3gwLZHnDemA&ab_channel=AdrijanaJovicicSavic",
    },
];

export { projects };
